# Generated by Django 4.2.6 on 2023-10-25 15:59

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateTimeField(verbose_name='launch date')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('LI', 'Live'), ('AR', 'Archived')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('order', core.fields.OrderField()),
                ('type', models.CharField(choices=[('SU', 'Survey'), ('DC', 'Discussion'), ('DI', 'Diary')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.tile')),
            ],
        ),
    ]
